//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Collect.rc
//
#define IDD_ABOUTBOX                    100
#define IDB_SPLASH                      102
#define IDR_COMMSET_TMPL                103
#define IDR_MAINFRAME                   128
#define IDD_STRINGLIST                  130
#define IDD_STRING_LIST                 130
#define IDD_TYPEDLIST                   131
#define IDD_TYPED_PTR_LIST              131
#define IDD_LIST                        132
#define IDD_INT_LIST                    132
#define IDD_DWORD_ARRAY                 133
#define IDD_TYPED_PTR_ARRAY             134
#define IDD_POINT_ARRAY                 135
#define IDD_MAP_STRING_TO_STRING        136
#define IDD_TYPED_PTR_MAP               137
#define IDD_MAP_DWORD_TO_MYSTRUCT       138
#define IDD_DIALOG_OPERATE_TOOLBAR      140
#define IDD_DIALOG_COMMAND_TOOLBAR      141
#define IDD_DIALOG_USER                 142
#define IDB_BIT_USER_LOG                143
#define IDD_DIALOG_COM                  147
#define IDC_LIST                        1000
#define IDC_ELEMENT                     1001
#define IDC_ADD                         1003
#define IDC_REMOVE                      1004
#define IDC_REMOVE_ALL                  1005
#define IDC_FIND                        1006
#define IDC_GET_AT                      1008
#define IDC_UPDATE                      1009
#define IDC_INT                         1010
#define IDC_FLOAT                       1012
#define IDC_STRING                      1013
#define IDC_STRING2                     1014
#define IDC_DWORD                       1015
#define IDC_X                           1016
#define IDC_Y                           1017
#define IDC_INSERT_BEFORE               1018
#define IDC_ADD_OR_UPDATE               1019
#define IDC_KEY                         1020
#define IDC_VALUE                       1021
#define IDC_EDIT1                       1024
#define IDC_BUTTON1                     1025
#define IDC_COMBO1                      1026
#define IDC_BUTTON_DATA_SAVE            1027
#define IDC_COMBO_COM_DATABIT           1027
#define IDC_COMBO_COM_RATE              1028
#define IDC_COMBO_COM_STOPBIT           1029
#define IDC_CHECK1                      1030
#define IDC_PROGRESS1                   1031
#define IDC_BTN_START_REAL              1032
#define IDC_COMBO_SCAN_MODEL            1039
#define IDC_SPIN1                       1041
#define IDC_EDIT2                       1042
#define IDC_SPIN2                       1043
#define IDC_SPIN3                       1044
#define IDC_SPIN4                       1045
#define IDC_EDIT3                       1046
#define IDC_EDIT4                       1047
#define IDC_COMBO_SCAN_MODEL_SELECT     1047
#define IDC_EDIT5                       1048
#define IDC_CHECK2                      1048
#define IDC_SPIN5                       1049
#define IDC_CHECK3                      1049
#define IDC_SPIN6                       1050
#define IDC_CHECK4                      1050
#define IDC_SPIN7                       1051
#define IDC_SPIN8                       1052
#define IDC_COMBO2                      1053
#define IDC_COMBO3                      1054
#define IDC_CHECK_START_SCAN            1055
#define IDC_COMBO_COM_NUM               1056
#define IDC_CHECK_COM_FLOW              1057
#define IDC_BUTTON_COMM_APPLY           1058
#define IDC_COMBO_PARITY                1059
#define IDC_STATIC_COMM_STATE_TIP       1061
#define IDC_COMBO_FRAME_CMD             1062
#define IDC_STATIC_FRAME_HEAD           1065
#define IDC_STATIC_FRAME_TAIL           1066
#define IDC_EDIT_FRAME_CHK              1067
#define IDC_EDIT_ANGLE                  1068
#define IDC_EDIT_START_ANGLE            1069
#define IDC_EDIT_STEP_LEN               1070
#define IDC_EDIT_END_ANGLE              1072
#define IDC_EDIT_CURWAVE_LEN            1076
#define IDC_EDIT_USEWAVE_LEN            1077
#define IDC_CHECK_CLCOKWISE             1078
#define IDC_BUTTON_DOWN_FRAME_CMD       1079
#define IDC_STATIC_FRAME_DISP           1080
#define IDC_LIST_TX_DATA                1081
#define IDC_LIST_RX_DATA                1083
#define IDC_EDIT_RX_DATA                1084
#define IDC_BTN_TEST_                   1085
#define IDC_BTN_RESET                   1087
#define IDC_BTN_STOP                    1088
#define IDC_BTN_WAVELEN_GOTO            1089
#define IDC_BTN_SPEED_SET               1090
#define IDC_EDIT_TEST                   1092
#define IDC_EDIT_OUTPUT                 1093
#define IDC_BTN_COLLECT                 1094
#define IDC_CMB_SPEED                   1095
#define IDC_CMB_WAVELEN                 1096
#define IDC_CMB_WAVELEN_OFFSET          1097
#define IDC_SPIN_WAVELEN_OFFSET         1098
#define IDC_EDIT_ONLINE                 1099
#define IDC_EDIT_CURWAVELEN             1100
#define IDC_EDIT_COLLECT                1101
#define IDC_LIST2                       1104
#define ID_STRINGLIST                   32774
#define ID_TYPEDLIST                    32775
#define ID_CLIST                        32776
#define ID_INTLIST                      32776
#define ID_DWORDARRAY                   32777
#define ID_TYPEDARRAY                   32778
#define ID_TYPEDPTRARRAY                32778
#define ID_ARRAY                        32779
#define ID_POINTARRAY                   32779
#define ID_MAPSTRINGTOSTRING            32780
#define ID_TYPEDPTRMAP                  32781
#define ID_MAP                          32782
#define ID_MAPBYTETOMYSTRUCT            32782
#define ID_MAPDWORDTOMYSTRUCT           32782
#define ID_GRAPH_VIEW                   32783
#define ID_ON_REAL                      32784
#define ID_TEST                         32785
#define ID_VIEW_OPER_BAR                32786
#define ID_MENU_USER                    32788
#define ID_COMMSET                      32789
#define IDS_INITIAL_STRING              57645
#define IDS_INITIAL_KEY                 57646
#define IDS_INITIAL_VALUE               57647
#define IDS_SELECT_DWORD_TO_UPDATE      57648
#define IDS_SELECT_DWORD_TO_REMOVE      57649
#define IDS_SELECT_INTEGER              57650
#define IDS_KEY_NOT_FOUND               57651
#define IDS_KEY_NOT_FOUND_CHOOSE_REMOVE_AGAIN 57652
#define IDS_SELECT_POINT_TO_BE_UPDATED  57653
#define IDS_SELECT_POINT_TO_BE_REMOVED  57654
#define IDS_SELECT_STRING_FIRST         57655
#define IDS_SELECT_ENTRY_TO_BE_UPDATED  57656
#define IDS_SELECT_ENTRY_TO_BE_REMOVED  57657
#define IDS_BLANK_CHARS_NOT_ALLOWED     57658
#define IDS_SELECT_ENTRY                57659

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        150
#define _APS_NEXT_COMMAND_VALUE         32790
#define _APS_NEXT_CONTROL_VALUE         1105
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
